### ISSUE TITLE
Many relations suddenly disappeared from waymarked trails hiking

### ISSUE THREAD

**Issue by ghost** [waymarkedtrails/waymarked-trails-site#462] opened 2024-06-21 17:13 UTC
There's a number of relations that I noticed suddenly disappeared from waymarked trails hiking map. This are the one I found after a short research:

https://www.openstreetmap.org/relation/2400483
https://www.openstreetmap.org/relation/4036923
https://www.openstreetmap.org/relation/4033771
https://www.openstreetmap.org/relation/4847689
https://www.openstreetmap.org/relation/4030225
https://www.openstreetmap.org/relation/4866988
https://www.openstreetmap.org/relation/4033774

Most of these relations have not been modified in months and they have the required tag to appear on waymarked trails (type=route+route=hiking)

I'm sure there are much more relations suffering this issue, is there a problem in the data synchronization between OSM and waymarked trails? Or am I missing something in mapping?

**Comment by lonvia** [comment] 2024-06-21 18:50
Duplicate of #461.

**Closed as completed by lonvia** 2024-06-21 18:50 UTC
