### ISSUE TITLE
Add support for USA hiking routes

### ISSUE THREAD

**Issue by Mashin6** [waymarkedtrails/waymarked-trails-site#354] opened 2020-05-31 02:52 UTC
1) Would it be possible to add more colors for `*_stripe` foreground option? Particularly these: pink/magenta, teal/cyan

2) Add support for second foreground symbol.
Most of main trails in USA are marked as vertical stripe without background e.g. `blue::blue_stripe`, but connectors or side trails have a small square on the bottom in second color e.g. `blue::blue_stripe:red_rectangle_lower`. 
This would also require to add support for new foreground symbol `*_rectangle_lower`.
Some visual examples can be found here https://wiki.openstreetmap.org/wiki/United_States/Long_distance_trails#Symbol_tags

**Comment by lonvia** [comment] 2020-08-26 08:08
Regarding 1): Colors are tricky. Looking at HTML color names, teal and cyan are vastly different. I'm leaning towards simply supporting all 16 HTML base color names (also referenced in https://wiki.openstreetmap.org/wiki/Key%3Acolour) and be done with it.

Regarding 2): from the pictures on the wiki page, I wonder if we shouldn't actually have a background of <color>_stripe, which results in a rectangular symbol instead of the usual square symbol. It's closer to the actual symbol and means that we wouldn't need a second foreground. Your example symbol could just be tagged as `blue:blue_stripe:red_rectangle_lower`.

**Comment by Mashin6** [comment] 2020-08-27 15:31
Thanks for your reply Sarah.
Ad 1) I think that is reasonable. Those cover vast majority of colors that I encountered so far. 

Ad2) I think that would work as well. Single color routes would then gave to be tagged as `blue:blue_stripe`. 
It seems that your rendering is ignoring the first part of osmc tag, but just make sure this would be compatible. Those two-color options I started tagging as `blue_yellow::blue_stripe:yellow_rectangle_lower` (the new way would be: `blue_yellow:blue_stripe:yellow_rectangle_lower`) to avoid confusion with nearby blue and yellow trails. 

3) Recently I came across a park that uses split diamonds. e.g. https://www.openstreetmap.org/relation/11528055  The only currently supported foreground is `black_red_diamond`. For now I tagged them as a version of this tag: `blue_white::blue_white_diamond`. What are your thoughts on `*_*_diamond` scheme?

**Comment by Mashin6** [comment] 2021-07-21 03:05
But it seems there are at least some foundations for second foreground support. I know only a bit of python so I don't know difficult it would be to make it work
 https://github.com/waymarkedtrails/waymarked-trails-site/blob/cdf06a65791657a61d9f3f8816cb7ee4fb685eff/db/common/symbols.py#L529-L536

**Comment by lonvia** [comment] 2021-07-23 08:51
The Isreali exception was an actual square symbol with three colors, so not quite the same. I still think having the basic shape right is a good idea.

Let me hack up something this weekend for both color and shape and see if we can put the tagging dispute to rest with the result.

**Comment by Mashin6** [comment] 2021-07-23 15:10
I talked to [Nop](https://www.openstreetmap.org/user/Nop) about the proposed new background shape and there was not much enthusiasm about it. Main argument was that it would destroy the scheme as it is defined.
Btw: you two (+OsmAnd) should come together and make some sort of "consortium" that would overlook the osmc scheme standars.

Looking at the code with my naive eyes, I looks like it would just needs to add one extra layer of shape drawing `if self.fg2symbol is not None: ...` that will reuse the code of the existing fg_symbol . And update logic to to distinguish cases like symbol with 1 fg shape, 2 fg shapes, 1 fg shape + text, 2 fg shapes + text.

**Comment by lonvia** [comment] 2021-07-23 15:41
I'm very reluctant to support the second foreground symbol schema because it is ambiguous and a pain to parse. If the osmc:symbol has four elements, is the last one a second foreground or a text? Oh, let's do some clever guessing based on the content! Not a fan.

Also, your currently used value of `blue::blue_stripe:red_rectangle_lower` does not really get you the expected result. Applying the foregrounds as you defined them, you get:

![blue_stripe_red_lower](https://user-images.githubusercontent.com/1447941/126805974-fa5cdc0d-ebd0-40e5-9c9f-87266249419c.png)

And that is not what you want. A stripe background would do the right thing.

**Comment by Mashin6** [comment] 2021-07-23 16:14
The distinction is tricky, but what about just basic:
* 1 fg shape => `len(parts) == 3`
* 2 fg shapes => `len(parts) == 4`
* 1 fg shape + text => `len(parts) == 5`
* 2 fg shapes + text => `len(parts) == 6`
* 0 fg shape + text => `len(parts) == 5` because it should still be e.g. `black:black::X29:white` (`black:black:X29:white` doesn't work on https://hiking.waymarkedtrails.org/help/rendering/osmc. If that it a bug in implementation then maybe something like `len(parts) == 4 & len(parts[2]) < 5` as max text of 4 characters are supported)

 
In your example `red_rectangle_lower` is rendered as `red_lower`. Its going to need a new `def paint_fg_rectangle_lower(self, ctx):` I could play with if I figure out how to run minimal part of your code without need to build the whole web site.

**Comment by Hufkratzer** [comment] 2021-07-23 18:02
> I'm very reluctant to support the second foreground symbol schema because it is ambiguous and a pain to parse. If the osmc:symbol has four elements, is the last one a second foreground or a text? Oh, let's do some clever guessing based on the content! 

The clever guessing could perhaps be: If the value is the name of a foreground symbol then assume that this is what is meant, else assume it is just a text. 

This rule could not only be applied to the 4th element, but also to the 3rd, see first two examples in https://wiki.openstreetmap.org/wiki/Key:osmc:symbol#Examples :
osmc:symbol=red:white:red_bar:FW:gray
osmc:symbol=black:black:X29:white

According to the 5th example (osmc:symbol=blue:shell_modern) the background symbol seems to be optional too. So for the 2nd element you may apply the rule: If the value is the name of a background symbol, then assume that this is what is meant, else assume it is the name of a foreground symbol.

**Comment by Mashin6** [comment] 2021-07-23 19:47
Yeah that seems like another viable option: have a list of shape names and then check if that name is in there. `if parts[3] in fg_symbol_names:`

**Comment by lonvia** [comment] 2021-07-23 20:04
You misunderstand: it's not that I wouldn't know how to implement some whacky algorithm that catches the corner cases, it's simply that I reserve the right to refuse to. The definition of osmc:symbol in the wiki is inconsistent and ill-defined. And the examples don't fit the definition either. Yes, I could make educated guesses based on the content but that means that you can never use a symbol waymarkedtrails doesn't implement without breaking the waymarkedtrails map. And that's bad design.

Regarding the symbols for this ticket, my proposal for a dedicated background shape stands. If that is not good enough, I'm open for other suggestions but the two-foreground solution just adds more exceptions and is therefore not feasible.

**Comment by Hufkratzer** [comment] 2021-07-24 10:53
> Yes, I could make educated guesses based on the content but that means that you can never use a symbol waymarkedtrails doesn't implement without breaking the waymarkedtrails map. And that's bad design.

Hm, yes, I hadn't considered that.

@Mashin6 : In 2010 there was a discussion about this on https://wiki.openstreetmap.org/wiki/DE_talk:Key:osmc:symbol. @lonvia had proposed to change the format to 
**osmc:symbol = waycolor :backgrund :foregrund [,foregrund2] :text :textcolour**
to avoid the problem; Nop had answered that he didn't think it was necessary because all symbol names were different. Maybe he didn't see the problem with different maps implementing different sets of symbols either at that time. 
For example, if WT would implement a foreground symbol "dog", which Nop's map doesn't know, and someone tags a route with osmc:symbol=red:red_frame:red_slash:dog the text "dog" may appear on his map, what was never intended.

**Comment by Mashin6** [comment] 2021-07-25 18:03
Oh I see.. I haven't been aware that there were some prior discussions about this. Was this ever brought to talk mailing list? It feels a bit like that Nop is treating the tag as a renderer specific tag, which goes against the OSM policy to not tag for a renderer.

The idea of `...:foreground,foreground2:...` is interesting. If applied to this problem then the advantage would be that the compatibility for the regular stripe symbols `blue::blue_stripe` would be preserved also for other maps. On the  other hand the new syntax `blue_red::blue_stripe,red_rectangle_lower` would be only recognized by waymarked trails map, but since it would not be rendered even with the original syntax anywhere then I guess that doesn't matter that much.

**Comment by lonvia** [comment] 2021-07-25 19:05
Looks like I need to make another thing clear: weather or not the situation with the two foreground symbols is solved, I still consider two foreground symbols an inappropriate solution for the situation at hand. So it is unlikely that I'll be adding a foreground symbol that is only needed because another foreground symbol is being abused for something it shouldn't.

The foreground `*_stripe` means that there is a stripe over the area of the symbol, i.e. right and left of the strip is an area which still belongs to the overall symbol. This simply is not the case here. You simply have a blue rectangular symbol with a red lower part. The area right and left of the blue part is not part of the symbol. So `blue:blue:red_lower` is exactly what is seen here. Abusing the foreground to influence the shape of the overall symbol is just wrong. (On Nop's map, your chosen osmc:symbol would get you a square blue shape incidentally because he has chosen a rectangular shape as base form.)

**Comment by lonvia** [comment] 2021-07-26 10:01
Hmm, rereading the discussion with Nop from 2010, he stated that the background is also optional:
```
osmc:symbol = waycolor :background [:foreground] [:foreground2] :text:textcolor
osmc:symbol = waycolor [:background] :foreground [:foreground2] [:text:textcolor]
```

So if you would be happy with using the `osmc:symbol=waycolor:foreground:foreground2` variant of that and write `blue:blue_stripe:red_lower` then waymarkedtrails can interpret that as `blue_stripe` background with `red_lower` foreground and be fully within the current specification. Introducing different base shapes on the map this way might be useful for other cases, too.

**Comment by Mashin6** [comment] 2021-07-26 21:24
`blue:blue:red_lower` would mean that it is a square shaped mark with top half blue and lower half red. The blazes are really a vertical stripe or a vertical stripe with about 1/3 of the bottom area in different color.

![image](https://user-images.githubusercontent.com/5265707/127061048-670a8981-01d6-423c-89b0-969e85889262.png)
![image](https://user-images.githubusercontent.com/5265707/127061099-fb700c99-57f6-4c4e-99da-8efb301ac381.png)

**Comment by Hufkratzer** [comment] 2021-07-27 06:04
> `blue:blue:red_lower` would mean that it is a square shaped mark with top half blue and lower half red.

@Mashin6 : Yes, but I think @lonvia wants you to use `blue:blue_stripe:red_lower` instead. This may later look like what you need on WT, but on Nop's map it will look different because there the `blue_stripe` will be interpreted as a foreground symbol and the second foreground symbol `red_lower` will be added in full size. I assume it would look like this:
![piesting_blue_red](https://user-images.githubusercontent.com/5958184/127099680-26102807-40df-43d1-ae64-8f9481907a5c.jpg)
(`red_lower` manually added to https://www.wanderreitkarte.de/index.php?lon=16.1117&lat=47.8754&zoom=17&lang=en)

This would make the whole situation even more confusing than it already is IMHO. [Earlier](https://github.com/waymarkedtrails/waymarked-trails-site/issues/354#issuecomment-885707255) you wrote that you talked to Nop. What did he propose to solve this problem?

Shouldn't the tag used for the second foreground rather be `<color>_stripe_lower` instead of `<color>_rectangle_lower` (because it has to have the width of the stripe what may differ from the width of a rectangle)?

**Comment by Mashin6** [comment] 2021-07-31 21:32
`osmc:symbol=waycolor:foreground:foreground2` seems fine to me even though the current wiki page does not reflect this use.
But with the `red_lower` I don't know... Currently all osmc:symbol implementations (and how majority mappers understand it) are working with predefined shapes inside a square canvas that get stacked on top of each other in order to produce the final shape. If one shape starts to modify how the following shape will be rendered, that will add a completely new functionality that no one is expecting and will also make it a bit more difficult to anticipate how the final shape will look like. (Also what if there is a symbol that looks exactly as that inverted red-blue T. How would it be distinguished from the blue-red stripe we are trying to achieve?) Plus as I said, it is not lower 1/2 but more like lower 1/3 that is different color. I still think that making a separate foreground shape is the easier solution.

Unfortunately Nop did not provide any ideas or feedback other than that he does not like it. I suggested him to join this github issue or our email conversation with Sarah and David Reik, but so far it didn't happen.

Hmm interesting, I was so concentrated on the square shape of that lower part that I totally missed an opportunity to relate it to the parent stripe shape. I actually really like the `<color>_stripe:<color>_stripe_lower` and I think I am going to update those tags in all the routes.

**Comment by lonvia** [comment] 2021-08-01 08:24
Well, the root cause of all the contention here is that the situation with the osmc:symbol is completely messed up. We have a wiki page that is completely out of line with what anyone does and that cannot be changed because Nop considers it his own private page. We have [waymarkedtrails' implementation](https://hiking.waymarkedtrails.org/help/rendering/osmc) which is based on the original definition of the tag before Nop suddenly came up with the foreground2 definition. We have an [implementation in OSMAnd](https://github.com/osmandapp/OsmAnd-tools/blob/612331937254b55035583c394b2236f27b18cf49/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java#L1268) which is kind of based on the current wiki page. And there is Nop's interpretation which nobody knows what it is. It simply doesn't help that you now come up with your own definition that is neither documented nor supported by anybody. So I'm going to close this ticket as 'request denied' on the ground that the symbol you want to use needs to be discussed and documented first.

So, if you are interested in following this up, I suggest to attack this on two fronts:

1. Get the osmc:symbol wiki page into a state that describes a consistent syntax that also reflects actual use. OSMAnd's usage looks half way sane, so I think that might be a good start and likely something I could agree on following up on waymarkedtrails (yes, including the second foreground).

2. Regarding your specific shield: please discuss this with the US hiking mapper community and get a general agreement how these stripe symbols are to be mapped. And I'd appreciate if during this discussion you also bring up my objections to your proposed schema. Once you have come to an agreement, make sure it is documented on a wiki page (with links to the relevant discussions). Preferably the osmc:symbol page gets updated as well. Once this is all done, please open a new issue linking to the documentation and we can discuss implementation.

Note that any symbols for 2) that rely on a second foreground depend on 1) being solved first.

**Closed by lonvia** 2021-08-01 08:24 UTC

**Comment by Mashin6** [comment] 2021-08-03 19:21
Look all I came here for was to get a support for a new foreground symbol that would allow to render that little square of our blazes. I really don't follow any more how do I come up with my own undocumented definition of osmc:symbol. 

If I am getting it right what you are pretty much asking me to do is to settle a years-long dispute between two people and get a community consensus over osmc:symbol tag. I think this is bit unreasonable to ask for. That's like telling someone that they have to first solve South and North Korea conflict before they can order a bowl of Bibimbap.

I have recently started a discussion on [OSMUS Slack](https://osmus.slack.com/archives/C1US5SFUH/p1626823573020100). I'll try to update it with the latest discussion here, but maybe you can join the thread and restate your arguments.

**Comment by lonvia** [comment] 2025-05-19 08:57
I've gone ahead and added support for a `*_stripe` background. Using that will result in a shield that is rectangular instead of square. Foregrounds can be used to add different colors:

![blue stripe with lower red rectangle](https://hiking.waymarkedtrails.org/api/v1/symbols/from_tags/NAT?osmc:symbol=blue%3Ablue_stripe%3Ared_lower%20)  `osmc:symbol=blue:blue_stripe:red_lower`

Consider this solution an offer. It is up to you to take it up or not. I don't mind either way.
