### ISSUE TITLE
cycle route not rendered and listed

### ISSUE THREAD

**Issue by ppete2** [waymarkedtrails/waymarked-trails-site#346] opened 2020-03-29 11:59 UTC
Please take a look at the following location https://cycling.waymarkedtrails.org/#routelist?map=17!48.2601!13.036

South of the river, right from the bridge cycle route R3 "Innweg" starts. Left of the bridge route R3a "Tauernweg (Oberösterreich)" starts. Why is R3 rendered in the map as well as listed in waymarkedtrails's Route list, and R3a not?

**Comment by lonvia** [comment] 2020-04-12 17:38
What is the OSM relation id for R3a?

**Comment by ppete2** [comment] 2020-04-12 17:43
https://www.openstreetmap.org/relation/8165768

**Comment by lonvia** [comment] 2020-04-12 17:58
It's there but it considered a section of https://www.openstreetmap.org/relation/1775071. This used to have a `network=ncn` which made 8165768 a section relation (same network). When the network got deleted the subrelations should have become major routes again, which did not happen. So there is an update bug here.

That said, removing the network tag from 1775071 does not sound right. A super route may have a larger importance than its containing routes but shouldn't have a smaller one.

**Comment by ppete2** [comment] 2020-04-12 18:29
1775071 in reality is a virtual "collection" of geographic divided individual signed routes of 2 Austrian federal states. There's no complete "Tauernweg" with identical name, signs, operators etc.

The individual routes (where 8165768 is one of them) are operated by 2 regional, different tourism organisations (11 routes by "SalzburgerLand Tourismus GmbH", 2 routes by "Oberösterreich Tourismus GmbH". So alle of them are rcn and independend routes containing their individual name, operator, ref.

The virtual superroute could have network tag "rcn" too, since each of its routes is of type "rcn". But is it necessary at all to ref-tag the superroute if its indivdual parts are already reg-tagged? and what if 1 route would be of type "lcn"? Then a theoretical "rcn"-Tag for the superroute wouldn't be totally correct.

**Comment by lonvia** [comment] 2020-04-13 07:05
If it is a collection, it shouldn't be there at all, see [Relations are not categories](https://wiki.openstreetmap.org/wiki/Relations/Relations_are_not_Categories). At the very least please do not tag it with `type=route`. It's close to impossible to get this stuff sorted out programmatically.

**Comment by ppete2** [comment] 2020-04-13 09:45
Well, I admit that the situation with superrealtion "Tauernradweg" is a special case. But this relation is not just an "unimportant" local route, but contains the major cycling route of Austrian's federal state "Salzburg". It's been created 2011, and many people worked on it and its routes. So it's not that easy to change it's features without further discussions on forum or Mailing lists. 
Salzburg's tourism is promoting this route, it even got an individual Website: https://www.tauernradweg.at/

There are 2 problems is see:

The first one is it's treatment within OSM. As I tried to exlplain the (super)route "Tauernradweg" is a ("virtual") tourism project (see Website above) builded by routes within 2 states (Salzburg, Oberösterreich). Within the state Salzburg it's also a "real" route with cycling signs (shieldposts) named "Tauernradweg". On the other hand within the state Oberösterreich the 2 real routes including shieldposts are named different and marked with different REF-numbers: 

a) "Tauernweg", ref R3a, https://www.openstreetmap.org/relation/8165768
b) "Innweg", ref R3, https://www.openstreetmap.org/relation/28482

Since all these routes are part of (tourism) Tauernradweg its maybe ok to put them into a superroute, at least the creators and mappers in the past have decided to do so. Although it's not the typical linear superoute with identical naming, reference, operators, real signposts with this name and so on.

But the second, more important problem is it's current behavoiur within waymarked trails:
Why is a) "Tauernweg" not rendered, and b) "Innweg" is rendered. Both have exactly the same status within the superrelation ""Tauernradweg".

**Comment by lonvia** [comment] 2020-04-14 18:15
Actually a duplicate of #325, so closing here. The comments about this being very difficult to fix still apply.

**Closed by lonvia** 2020-04-14 18:15 UTC
