### ISSUE TITLE
Issues with displaying of routes in North America

### ISSUE THREAD

**Issue by mgefst** [waymarkedtrails/waymarked-trails-site#460] opened 2024-06-15 09:46 UTC
![Screenshot 2024-06-15 114327](https://github.com/waymarkedtrails/waymarked-trails-site/assets/18249379/ed9cd448-50c2-4f17-813a-a74cd3556c1f)

There is an issue displaying routes in the western half of North America. I have tried with multiple browsers.

Please see photo.

**Comment by lonvia** [comment] 2024-06-16 08:08
Duplicate of #458.

**Closed as completed by lonvia** 2024-06-16 08:08 UTC
