### ISSUE TITLE
Use of osmc:symbol in mtb and bicycle routes

### ISSUE THREAD

**Issue by amadvance** [waymarkedtrails/waymarked-trails-site#432] opened 2023-02-26 17:09 UTC
It seems that the "osmc:symbol" is only used for hiking routes, and not for MTB and bicycle routes. I wonder if there is a specific reason for this, and whether its use can be extended to those routes as well.

It is common to have routes that have both a hiking and cycling variant, and it would be great to be able to display them in the same way.

Thanks!

**Comment by lonvia** [comment] 2023-02-26 19:37
Duplicate of #223.

If you have more specific examples than 'it is common', please add them there and I consider to reopen.

**Closed as completed by lonvia** 2023-02-26 19:37 UTC

**Comment by amadvance** [comment] 2023-02-27 07:26
Added examples in #223
