### ISSUE TITLE
Suggestion: add check boxes to select/unselect types of networks

### ISSUE THREAD

**Issue by gerdami** [waymarkedtrails/waymarked-trails-site#201] opened 2014-09-15 09:52 UTC
Could be in the Routes popup: 3 check boxes to select/unselect
- national networks (network : nwn)
- regional networks (network : rwn)
- local networks (network : lwn)

in order to light crowded maps.

**Comment by pelderson** [comment] 2019-05-02 13:33
![image](https://user-images.githubusercontent.com/38458314/57078591-d1d62780-6cee-11e9-94dc-27bc689c2569.png)
The problem is increasing...
Is a separate map for the walking node networks an option? Those are the main problem in Nederland, and you really don't need to see long hiking routes and node networks in one view.

**Comment by lonvia** [comment] 2019-05-12 09:04
A new category for relations within node network sounds like a good idea. We'd have to tag them appropriately first. Either have a separate value for `network` or a new tag altogether. Would be go to discuss on a more global scale as node networks are increasingly popular, see also [this talk (in German) during last FOSSGIS)](https://pretalx.com/fossgis2019/talk/GP8WDX/).

**Comment by Hufkratzer** [comment] 2019-05-12 14:21
> Is a separate map for the walking node networks an option? Those are the main problem in Nederland, and you really don't need to see long hiking routes and node networks in one view.

I can't imagine what the improvement of having two separate maps would be. Is walking on a node network route much different than on a long distance hiking route? I doubt that and I think one map that contains all relevant information for one kind of activity is more convenient to use that several separate maps.

**Comment by lonvia** [comment] 2019-05-12 14:41
Oh separate map? No. I was thinking of simply a different style and a different handling in the route list.

**Comment by pelderson** [comment] 2019-05-12 18:04
Well, whatever the solution, just look at the picture to see the problem: you can't see the map because of the sheer number of routes. The main problem is that node networks are too prominent. And yes, for planning and using hiking routes, node networks are very different from long routes. I don't know any hikers who like to see node networks on the map (numbered nodes yes, route segments no) , and people who use node networks use special node network planners, not waymarked trails.

**Comment by pelderson** [comment] 2019-05-12 18:10
> Oh separate map? No. I was thinking of simply a different style and a different handling in the route list.

How would that help, how would it de-clog the hiking map?

**Comment by pelderson** [comment] 2019-05-15 13:24
> A new category for relations within node network sounds like a good idea. We'd have to tag them appropriately first. Either have a separate value for `network` or a new tag altogether. Would be go to discuss on a more global scale as node networks are increasingly popular, see also [this talk (in German) during last FOSSGIS)](https://pretalx.com/fossgis2019/talk/GP8WDX/).

I started a topic in the NL OSM forum about the idea, to explore the idea of a new network value for node networks. I suggested wnn for walking node network. network=cnn for cycling node network would be logical.

**Comment by pelderson** [comment] 2019-08-10 07:39
While this idea of a separate network-tag for node networks simmers, could the node networks be rendered from a higher zoomlevel for the Netherlands? Routes first visible at zoom 12 would make the map much better. Numbered nodes at zoom 13 like it is now, that's fine.

**Comment by lonvia** [comment] 2020-08-26 08:29
Closing this. "Uncrowding the map" needs a more generic solution that does not require user interaction.

**Closed by lonvia** 2020-08-26 08:29 UTC
