### ISSUE TITLE
Use Sonny's LiDAR elevation data instead of SRTM in Europe

### ISSUE THREAD

**Issue by ppete2** [waymarkedtrails/waymarked-trails-site#404] opened 2021-12-30 15:07 UTC
An idea: 

Could you use Sonny's Digital LiDAR-Terrain Models of Europe https://data.opendataportal.at/dataset/dtm-europe instead of SRTM/ASTER GDEM within Europe? These elevation models a far more precise than SRTM/ASTER - espcially in mountainous and/or wooden terrain. This will improve accuracy of elevation diagram and routes' accumulated elevation values on WMT. 

The file format (.hgt) is the same as with SRTM files, so you could use the same scripts as before to process them.

**Comment by lonvia** [comment] 2021-12-30 15:37
Duplicate of #269.

**Closed by lonvia** 2021-12-30 15:37 UTC
