### ISSUE TITLE
Route shown to be twice as long as it actually is (repeats loop in the other direction)

### ISSUE THREAD

**Issue by trougnouf** [waymarkedtrails/waymarked-trails-site#401] opened 2021-12-29 18:19 UTC
This hike https://hiking.waymarkedtrails.org/#route?id=6359959 I just came back from appears to be twice as long as it actually is (23 km vs ~11.5).
The elevation map shows that the loop starts over in the other direction once it's done.
I don't know if it's a bug here or the route was badly entered on OpenStreetMap but I didn't find anything wrong with the data.

**Comment by lonvia** [comment] 2021-12-29 19:22
The relation in OSM looks to be correct, so probably a bug in waymarkedtrails somewhere.

**Comment by ppete2** [comment] 2021-12-30 14:11
I can confirm this bug, also Nordic slope "Zölskogelloipe" https://slopes.waymarkedtrails.org/#route?id=8020328&type=relation&map=15.0/47.7216/14.3301 has twice of its correct length. I noticed that just 2 of 4 slopes in this area are wrong. Maybe because these 2 slopes consist of some OSM-ways which are multiple times used in the relation, whereas the 2 correct ones are "true" roundtrips where each OSM-way is exactly 1 time part within the relation.

**Comment by lonvia** [comment] 2021-12-30 22:36
Fixed in https://github.com/waymarkedtrails/osgende/commit/f87debe2fa6804180706c7546364df42ba62e280.

**Closed by lonvia** 2021-12-30 22:36 UTC
