### ISSUE TITLE
Add support for fitness_trail

### ISSUE THREAD

**Issue by Nekzuris** [waymarkedtrails/waymarked-trails-site#396] opened 2021-09-30 00:20 UTC
Fitness trail are currently not displayed, maybe they can be added to hiking or in their own category.

**Comment by lonvia** [comment] 2021-09-30 06:54
Duplicate of #219.

**Closed by lonvia** 2021-09-30 06:54 UTC

**Comment by pyrog** [comment] 2024-03-25 11:24
Fitness trails could be displayed on the hiking style for the moment.
See https://github.com/waymarkedtrails/waymarked-trails-site/issues/408#issuecomment-1012014995
