### ISSUE TITLE
Render running routes

### ISSUE THREAD

**Issue by pyrog** [waymarkedtrails/waymarked-trails-site#456] opened 2024-03-25 11:29 UTC
[route=running](https://wiki.openstreetmap.org/wiki/Tag:route%3Drunning) should be displayed in hiking style for the moment.
And better they could be rendered in their own style later.

See https://github.com/waymarkedtrails/waymarked-trails-site/issues/219#issuecomment-1016654759, https://github.com/waymarkedtrails/waymarked-trails-site/issues/396#issuecomment-2017786450 and https://github.com/waymarkedtrails/waymarked-trails-site/issues/408#issuecomment-1012014995

**Comment by lonvia** [comment] 2024-03-25 12:50
Opening more and more issues won't make this happen any faster. The hiking map is already too full as it is.

Closing as duplicate of #219.

**Closed as not planned by lonvia** 2024-03-25 12:50 UTC
