### ISSUE TITLE
Cycling background layer updates delayed?

### ISSUE THREAD

**Issue by robhubi** [waymarkedtrails/waymarked-trails-site#335] opened 2019-12-08 16:14 UTC
I’ve added a guidepost on Dec. 6th. Till now it hasn't been visible in the background layer, but it is clickable: https://cycling.waymarkedtrails.org/#guidepost?id=7039513757  

Last update time is given to: 8.Dez. 2019 16:51:02 (actual time is 8. Dez. 2019 16:52)

It’s also visible in CyclOSM: https://www.cyclosm.org/#map=19/47.20799/14.67850/cyclosm and in some other maps, but not in waymarked trails.

Best regards
Robert

**Comment by lonvia** [comment] 2019-12-15 15:02
The issue is actually that it used to be tagged as a node network node and has been changed to a guidepost. Looks like this retagging was not picked up by the node network table. I'm looking into that.

**Comment by lonvia** [comment] 2019-12-15 20:35
Should be fixed now. I've removed the spurious nodes from the database.

**Closed by lonvia** 2019-12-15 20:35 UTC

**Comment by robhubi** [comment] 2019-12-15 22:10
I see, the issue has gone. Thanks a lot.
Robert
